employee/urls.py
"""urls for employee application."""

from django.urls import path

from employee.views import (
    employee_add_view,
    employee_delete_view,
    employee_detail_view,
    employee_list_view,
    employee_update_view
)

app_name = 'employee'

urlpatterns = [
    path('employees/', employee_list_view, name='employees'),
    path('employee/<int:id>/', employee_detail_view, name='employee_detail'),
    path('employee/add/', employee_add_view, name='employee_add'),
    path('employee/update/<int:id>/', employee_update_view, name='employee_update'),
    path('employee/delete/', employee_delete_view, name='employee_delete'),
]

order/urls.py
"""urls for order application."""

from django.urls import path

from order.views.order_views import order_add_view, order_detail_view, order_list_view, order_update_view
from order.views.task_views import task_add_view, task_delete_view, task_detail_view, task_list_view, task_update_view

app_name = 'order'

urlpatterns = [
    path('orders/', order_list_view, name='orders'),
    path('order/<int:id>/', order_detail_view, name='order_detail'),
    path('order/add/<int:client_id>/', order_add_view, name='order_add'),
    path('order/update/<int:id>/', order_update_view, name='order_update'),

    # TASK URLS
    path('tasks/', task_list_view, name='tasks'),
    path('task/<int:id>/', task_detail_view, name='task_detail'),
    path('task/add/<int:order_id>/', task_add_view, name='task_add'),
    path('task/update/<int:id>/', task_update_view, name='task_update'),
    path('task/delete/', task_delete_view, name='task_delete'),
]

tms/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('tailor_management_system.urls')),
    path('', include('client.urls')),
    path('', include('order.urls')),
    path('', include('employee.urls')),
    path('', include('product.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

order/models.py
"""Models for order application."""

from django.db import models

from client.models import Client
from employee.models import Employee
from product.models import Product


class Order(models.Model):
    """Order model."""

    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, blank=True, default=None, null=True, on_delete=models.CASCADE)

    RECIEVED, IN_PROGRESS, DELIVERED, CLOSED = 'R', 'I', 'D', 'C'
    ORDER_STATUS_CHOICES = [(RECIEVED, 'Recieved'), (IN_PROGRESS, 'In Progress'),
                            (DELIVERED, 'Delivered'), (CLOSED, 'Closed')]

    status = models.CharField(
        max_length=1,
        choices=ORDER_STATUS_CHOICES,
        default=RECIEVED
    )
    payment_status = models.BooleanField(default=False)
    payment_amount = models.PositiveSmallIntegerField()
    advance_payment_amount = models.PositiveSmallIntegerField(default=0, blank=True)
    delivery_date = models.DateField(blank=True, null=True)
    date_recieved = models.DateField(auto_now_add=True)
    order = models.CharField(max_length=50)
    instructions = models.TextField(max_length=500, blank=True, null=True)

    objects = models.Manager()

    def __str__(self):
        """Convert object to String."""
        return 'Id:{} - DeliveryDate:{} - ClientName:{}'.format(
            self.id,
            self.delivery_date,
            self.client.name
        )


class Task(models.Model):
    """Task Model."""

    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, null=True, blank=True, on_delete=models.SET_NULL)
    description = models.TextField(max_length=500)

    CREATED, IN_PROGRESS, COMPLETED = 'CR', 'I', 'C'
    TASK_STATUS_CHOICES = [(CREATED, 'Created'), (IN_PROGRESS, 'In Progress'), (COMPLETED, 'Completed')]

    status = models.CharField(max_length=2, choices=TASK_STATUS_CHOICES, default=CREATED)
    deadline = models.DateField()
    objects = models.Manager()

    def __str__(self):
        """Convert object to String."""
        return 'OrderId:{} - EmployeeName:{} - Deadline:{} - Task:{}'.format(
            self.order_id.id,
            self.employee_id.name,
            self.deadline,
            self.description
        )

order/forms.py
"""Forms for order application."""

import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.forms.widgets import SelectDateWidget

from order.models import Order, Task


class OrderForm(forms.ModelForm):
    """Order model mapped form."""

    order = forms.CharField(max_length=50, min_length=5)
    instructions = forms.CharField(widget=forms.Textarea, max_length=500, min_length=10)
    delivery_date = forms.DateField(widget=SelectDateWidget(empty_label="Delivery Date"))

    class Meta:
        """Specify fields to include."""

        model = Order
        exclude = ('date_recieved', 'client')

    def clean_delivery_date(self):
        """Check if date is valid."""
        delivery_date = self.cleaned_data['delivery_date']
        if delivery_date < datetime.date.today():
            raise ValidationError(('Delivery date can not be in past.'))

        return delivery_date

    def clean_status(self):
        """Check if status is valid."""
        status = self.cleaned_data['status']

        if (status == Order.DELIVERED) or (status == Order.CLOSED):
            incomplete_task_count = Task.objects.exclude(status=Task.COMPLETED).count()
            if incomplete_task_count:
                raise ValidationError(('Some tasks against this order are still pending, please finish them first.'))

        return status


class TaskForm(forms.ModelForm):
    """Task model mapped form."""

    description = forms.CharField(widget=forms.Textarea, max_length=500, min_length=10)
    deadline = forms.DateField(widget=SelectDateWidget(empty_label="Deadline"))

    class Meta:
        """Specify fields to include."""

        model = Task
        exclude = ('order',)

    def clean_deadline(self):
        """Check if date is valid."""
        deadline = self.cleaned_data['deadline']

        if deadline < datetime.date.today():
            raise ValidationError(('Deadline can not be in past.'))

        return deadline

order/views/order_views.py
"""Views for order application."""

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from rest_framework.views import View

from client.models import Client
from order.forms import OrderForm
from order.models import Order, Task


class OrderListView(LoginRequiredMixin, View):
    """Class based view for Order for listing all the orders."""

    def get(self, request):
        """Render order list template.."""
        orders = Order.objects.exclude(status=Order.CLOSED)
        context = {
            'orders': orders,
        }
        return render(request, 'order/list-orders.html', context)


order_list_view = OrderListView.as_view()


class OrderDetailView(LoginRequiredMixin, View):
    """Class based view for Order for detail of order."""

    def get(self, request, id):
        """Render order detail tempalte.."""
        order = Order.objects.get(id=id)
        tasks = Task.objects.filter(order=order)
        context = {
            'order': order,
            'tasks': tasks
        }
        return render(request, 'order/order-detail.html', context)


order_detail_view = OrderDetailView.as_view()


class OrderAddView(LoginRequiredMixin, View):
    """Class based view for adding new order."""

    def get(self, request, client_id):
        """Return add new order form."""
        client = get_object_or_404(Client, id=client_id)
        form = OrderForm()
        return render(request, 'order/add-order.html',
                      {'form': form, 'func': 'Add', 'client': client})

    def post(self, request, client_id):
        """Save order and redirect to order list."""
        form = OrderForm(request.POST)
        client = get_object_or_404(Client, id=client_id)
        if form.is_valid():
            new_order = form.save(commit=False)
            new_order.client = client
            new_order.save()
            return redirect('order:orders')
        else:
            return render(request, 'order/add-order.html', {'form': form, 'func': 'Add', 'client': client})


order_add_view = OrderAddView.as_view()


class OrderUpdateView(LoginRequiredMixin, View):
    """Class based view for updating new order."""

    def get(self, request, id):
        """Return add new order form."""
        order = get_object_or_404(Order, id=id)
        form = OrderForm(instance=order)
        return render(request, 'order/add-order.html',
                      {'form': form, 'func': 'Update', 'order': order})

    def post(self, request, id):
        """Save order and redirect to order list."""
        order = get_object_or_404(Order, id=id)
        client = get_object_or_404(Client, id=order.client.id)
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            new_order = form.save(commit=False)
            new_order.client = client
            new_order.save()
            return redirect('order:orders')
        else:
            return render(request, 'order/add-order.html', {'form': form, 'func': 'Update', 'order': order})


order_update_view = OrderUpdateView.as_view()

order/views/task_views.py
"""Views for order application."""

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from rest_framework.views import View

from order.forms import TaskForm
from order.models import Order, Task


class TaskListView(LoginRequiredMixin, View):
    """Class based view for Order for listing all the orders."""

    def get(self, request):
        """Render task list template.."""
        tasks = Task.objects.all()
        context = {
            'tasks': tasks,
        }
        return render(request, 'task/list-tasks.html', context)


task_list_view = TaskListView.as_view()


class TaskDetailView(LoginRequiredMixin, View):
    """Class based view for tasks for detail of tasks."""

    def get(self, request, id):
        """Render tasks detail tempalte.."""
        task = Task.objects.get(id=id)
        context = {
            'task': task,
        }
        return render(request, 'task/task-detail.html', context)


task_detail_view = TaskDetailView.as_view()


class TaskAddView(LoginRequiredMixin, View):
    """Class based view for adding new task."""

    def get(self, request, order_id):
        """Return add new task form."""
        order = get_object_or_404(Order, id=order_id)
        form = TaskForm()
        return render(request, 'task/add-task.html',
                      {'form': form, 'func': 'Add', 'order': order})

    def post(self, request, order_id):
        """Save task and redirect to task list."""
        form = TaskForm(request.POST)
        order = get_object_or_404(Order, id=order_id)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.order = order
            new_task.save()
            return redirect('order:tasks')
        else:
            return render(request, 'task/add-task.html', {'form': form, 'func': 'Add', 'order': order})


task_add_view = TaskAddView.as_view()


class TaskUpdateView(LoginRequiredMixin, View):
    """Class based view for updating new task."""

    def get(self, request, id):
        """Return add new task form."""
        task = get_object_or_404(Task, id=id)
        form = TaskForm(instance=task)
        return render(request, 'task/add-task.html',
                      {'form': form, 'func': 'Update', 'task': task})

    def post(self, request, id):
        """Save order and redirect to task list."""
        task = get_object_or_404(Task, id=id)
        order = get_object_or_404(Order, id=task.order.id)
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.order = order
            new_task.save()
            return redirect('order:tasks')
        else:
            return render(request, 'task/add-task.html', {'form': form, 'func': 'Update', 'task': task})


task_update_view = TaskUpdateView.as_view()


class TaskDeleteView(LoginRequiredMixin, View):
    """Class based view for tasks for deletion of task."""

    def post(self, request):
        """Render task list tempalte after deletion."""
        id = request.POST.get('id')
        task = get_object_or_404(Task, id=id)
        task.delete()
        return redirect('order:tasks')


task_delete_view = TaskDeleteView.as_view()

order/templates/task/add-task.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}
{% block content %}
<!-- begin:: Content -->
<div class="kt-container  kt-grid__item kt-grid__item--fluid">

    <!--begin::Portlet-->
    <div class="kt-portlet">
        <div class="kt-portlet__head">
            <div class="kt-portlet__head-label">
                <h3 class="kt-portlet__head-title">
                    Add Details
                </h3>
            </div>
        </div>

        <!--begin::Form-->
        {% if func == "Add" %}
        <form class="kt-form kt-portlet__body" action="{% url 'order:task_add' order.id %}" method="post">
        {% else %}
        <form class="kt-form kt-portlet__body" action="{% url 'order:task_update' task.id %}" method="post">
        {% endif %}    
            {% csrf_token %}
            {{ form|crispy }}
            <div class="kt-portlet__foot">
                <div class="kt-form__actions">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="reset" class="btn btn-secondary">Reset</button>
                </div>
            </div>
        </form>

        <!--end::Form-->
    </div>

    <!--end::Portlet-->
</div>

<!-- end:: Content -->
{% endblock %}

order/templates/task/list-tasks.html
{% extends 'base.html' %}
{% load static %}
{% load clean_title %}
{% load get_status %}
{% block content %}
<!-- begin:: Content -->
<div class="kt-container  kt-grid__item kt-grid__item--fluid">
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__body">

            <!--begin: Search Form -->
            <div class="kt-form kt-form--label-right kt-margin-t-2 kt-margin-b-10">
                <div class="row align-items-center">
                    <div class="col-xl-8 order-2 order-xl-1">
                        <div class="row">
                            <div style="padding-left:6%" class="col-md-4 kt-margin-b-20-tablet-and-mobile">
                                <div class="kt-input-icon kt-input-icon--left">
                                    <input type="text" class="form-control" placeholder="Search..." id="generalSearch">
                                    <span class="kt-input-icon__icon kt-input-icon__icon--left">
                                        <span><i class="la la-search"></i></span>
                                    </span>
                                </div>
                            </div>
                            <div class="col-md-4 kt-margin-b-20-tablet-and-mobile">
                                <div class="kt-form__group kt-form__group--inline">
                                    <div class="kt-form__label">
                                        <label>Status:</label>
                                    </div>
                                    <div class="kt-form__control">
                                        <select class="form-control bootstrap-select" id="kt_form_status">
                                            <option value="">All</option>
                                            <option value="1">Created</option>
                                            <option value="2">Completed</option>
                                            <option value="3">In Progress</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!--end: Search Form -->
        </div>
        <div class="kt-portlet__body kt-portlet__body--fit">

            <!--begin: Datatable -->
            <table class="kt-datatable table-striped" width="100%">
                <thead class="thead-dark">
                    <tr>
                        <th title="Field #1">Id</th>
                        <th title="Field #2">Order#</th>
                        <th title="Field #4">Assigned To</th>
                        <th title="Field #5">Deadline</th>
                        <th title="Field #6">Status</th>
                        <th title="Field #7">Actions</th>
                        <th>Hidden</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in tasks %}
                    <tr>
                        {% get_status "TASK" task.status as task_status_word %}
                        <td>{{ task.id }}</td>
                        <td>{{ task.order.id }}</td>
                        {% if task.employee %}
                        <td>{{ task.employee.name }}</td>
                        {% else %}
                        <td>Unassigned</td>
                        {% endif %}
                        <td>{{ task.deadline }}</td>
                        <td>{{ task_status_word }}</td>
                        <td data-field="Field #7" data-autohide-disabled="false" class="kt-datatable__cell"><span
                                style="overflow: visible; position: relative; width: 110px;">
                                <a href="{% url 'order:task_detail' task.id %}" title="View"
                                    class="btn btn-sm btn-clean btn-icon btn-icon-md">
                                    <i class="la la-file-text"></i>
                                </a>
                                <a href="{% url 'order:task_update' task.id %}" title="Edit"
                                    class="btn btn-sm btn-clean btn-icon btn-icon-md">
                                    <i class="la la-edit"></i>
                                </a>
                                <a title="Delete" class="btn btn-sm btn-clean btn-icon btn-icon-md delete-element-class"
                                    onclick="delOnClick(this)"
                                    id="{{ task.id }}">
                                    <i class="la la-trash"></i>
                                </a>
                            </span></td>
                        <td>Hidden</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <!--end: Datatable -->
        </div>
    </div>
</div>

<!-- end:: Content -->
{% endblock %}

{% block page-scripts %}
<script src="{% static 'js/pages/crud/metronic-datatable/base/html-table.js' %}" type="text/javascript"></script>
<script>
    function delOnClick(ref) {
        var url = "{% url 'order:task_delete' %}"
        var id = $(ref).attr("id")
        var intId = parseInt(id)
        var data = { id: intId, csrfmiddlewaretoken: '{{ csrf_token }}', contentType: 'application/json' }
        $.post(url, data, function (data, status) {
            location.reload(true)
        })
    }
</script>
{% endblock %}

order/templates/task/task-detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}
{% block content %}
<!-- begin:: Content -->
<div class="kt-container  kt-grid__item kt-grid__item--fluid">
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet overflow:auto">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">
                        Task#{{ task.id }}'s Information
                    </h3>
                </div>
            </div>
            <div class="row">
                <!-- Begin employee Info Column -->
                <div class="col-sm-12 text-center">
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <td align=right><b>Order Id:</b></td>
                                <td align=left><a href="{% url 'order:order_detail' task.order.id %}">{{ task.order.id }}</a></td>
                            </tr>
                            <tr>
                                <td align=right><b>Assigned to:</b></td>
                                {% if task.employee %}
                                <td align=left><a href="{% url 'employee:employee_detail' task.employee.id %}">{{ task.employee.name }}</a></td>
                                {% else %}
                                <td align=left>Unassigned.</td>
                                {% endif %}
                            </tr>
                            <tr>
                                <td align=right><b>Description:</b></td>
                                <td align=left>{{ task.description }}</td>
                            </tr>
                            <tr>
                                <td align=right><b>Deadline:</b></td>
                                <td align=left>{{ task.deadline }}</td>
                            </tr>
                        </tbody>
                    </table>
                    <a href="{% url 'order:task_update' task.id %}" class="text-center btn-outline-primary"> <Button
                            class="btn btn-primary">Update</Button></a>
                </div>
            </div>

            </br>

        </div>
    </div>

    <!-- end:: Content -->
    {% endblock %}

    {% block page-scripts %}
    <script src="{% static 'js/pages/crud/metronic-datatable/base/html-table.js' %}" type="text/javascript"></script>
    {% endblock %}